1. Read Raw Data .xlsx, then take column country, iso_code, year, and population

In [5]:
import pandas as pd 

path = "D:/Personal/Project/World Energy/Dataset/Raw Data/owid-energy-data.xlsx"
df = pd.read_excel(path, usecols=["country", "iso_code", "year", "population"])

df.head()

         country  year iso_code  population
0  ASEAN (Ember)  2000      NaN         NaN
1  ASEAN (Ember)  2001      NaN         NaN
2  ASEAN (Ember)  2002      NaN         NaN
3  ASEAN (Ember)  2003      NaN         NaN
4  ASEAN (Ember)  2004      NaN         NaN

2. Set year 1974 - 2024

In [6]:
df = df[(df['year'] >= 1974) & (df['year'] <= 2024)]

df.head()

         country  year iso_code  population
0  ASEAN (Ember)  2000      NaN         NaN
1  ASEAN (Ember)  2001      NaN         NaN
2  ASEAN (Ember)  2002      NaN         NaN
3  ASEAN (Ember)  2003      NaN         NaN
4  ASEAN (Ember)  2004      NaN         NaN

3. Handle missing value

In [7]:
def clean_data(df):
    # Drop rows with missing data in column: 'iso_code'
    df = df.dropna(subset=['iso_code'])
    # Replace gaps forward from the previous valid value in: 'population'
    df = df.fillna({'population': df['population'].ffill()})
    return df

df_clean = clean_data(df.copy())
df_clean.head()

         country  year iso_code  population
99   Afghanistan  1974      AFG  12469127.0
100  Afghanistan  1975      AFG  12773966.0
101  Afghanistan  1976      AFG  13059861.0
102  Afghanistan  1977      AFG  13340758.0
103  Afghanistan  1978      AFG  13611444.0

4. Export to excel file

In [8]:
df_clean.to_excel("clean_population.xlsx", index=False)

print("File completed saved!")

File completed saved!